<footer>
    <div class="bed_page">
        <div class="helpcenter">
            <dl>
                <dt>aaaaa</dt>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
            </dl>
            <dl>
                <dt>aaaaa</dt>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
            </dl>
            <dl>
                <dt>aaaaa</dt>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
            </dl>
            <dl>
                <dt>aaaaa</dt>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
            </dl>
            <dl>
                <dt>aaaaa</dt>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
                <dd>bbbbb</dd>
            </dl>
        </div>
    </div>
    <div class="footer">
        <ul>
            <li><a href="http://127.0.0.1/git_work/www.beddingonbed.com/about-magento-demo-store">About Us</a></li>
            <li><a href="http://127.0.0.1/git_work/www.beddingonbed.com/customer-service">Customer Service</a></li>
            <li class="last privacy"><a href="http://127.0.0.1/git_work/www.beddingonbed.com/privacy-policy-cookie-restriction-mode">Privacy Policy</a></li>
        </ul>
        <address><?php echo $this->getCopyright() ?></address>
        <div class="list-footer">
            <ul class="fcenter">
                <li class="ic ic_visa"></li>
                <li class="ic ic_master"></li>
                <li class="ic ic_lastschrift"></li>
                <li class="ic ic ic_discover"></li>
                <li class="ic ic_paypal"></li>
                <li class="ic ic_express"></li>
                <li class="ic ic_jcb"></li>
                <li class="ic ic_bleue"></li>
                <li class="ic ic_transfer"></li>
                <li class="ic ic_western"></li>
                <li class="ic ic_qwiki"></li>
                <li class="ic ic_delta"></li>
                <li class="ic ic_carte"></li>
                <li class="ic ic_giropay"></li>
                <li class="ic ic_sofort"></li>
                <li class="ic ic_dhl"></li>
                <li class="ic ic_ups"></li>
                <li class="ic ic_versg"></li>
                <li class="ic ic_norton"></li>
            </ul>
        </div>
    </div>
</footer>

<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/js.phtml')->toHtml(); ?>
