<header>

    <div class="bed_top">
        <div class="a-center">
            <?php
            $top_promotion = Mage::getModel('ibanners/group')->loadByCode('top_promotion')->getBannerCollection();
            foreach($top_promotion as $tp){
                echo $tp->getHtml();
            }
            ?>
        </div>
        <div class="top_help"><a href="<?php echo $this->getUrl('help')?>">Help</a></div>
    </div>

    <div class="bed_middle">
        <div class="web_log">
            <?php if ($this->getIsHomePage()):?>
                <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>
        </div>

        <div class="header_search">
            <?php $catalogSearchHelper =  $this->helper('catalogsearch'); ?>
            <form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
                <input id="search"
                       type="text"
                       name="<?php echo $catalogSearchHelper->getQueryParamName() ?>"
                       value="<?php echo $catalogSearchHelper->getEscapedQueryText() ?>"
                       class="input-text"
                       maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>"
                    />
                <input type="submit" name="sub_btn" value="Search" class="sub_btn"/>
                <script type="text/javascript">
                    //<![CDATA[
                    var searchForm = new Varien.searchForm('search_mini_form', 'search', 'Find anything for your home...');
                    //]]>
                </script>
            </form>
        </div>

        <div class="header_right">
            <a class="header_cart" href="<?php echo $this->getUrl('checkout/cart')?>">
                <i>0</i>
                <span>Cart</span>
            </a>
            <a class="header_account" href="<?php echo $this->getUrl('customer/account')?>">
                <i></i>
                <span>Account</span>
            </a>
        </div>

    </div>

    <nav>
        <div class="category_menu">
            <ul>
<!--                <li><a href="--><?php //echo $this->getUrl();?><!--">home</a></li>-->
                <?php
                $menu_tops = Mage::getModel('catalog/category')
                    ->setStoreId(Mage::app()->getStore()->getId())
                    ->load(2)
                    ->getChildrenCategories();
                ?>
                <?php foreach($menu_tops as $menu):?>
                    <li>
                        <a href="<?php echo $menu->getUrl();?>"><?php echo $menu->getName();?></a>
                        <div class="level2">
                            <?php echo $this->getLayout()->createBlock('cms/block')
                                ->setBlockId($menu->getUrlKey())
                                ->toHtml() ?>
                        </div>
                    </li>
                <?php endforeach;?>
            </ul>
        </div>
    </nav>

</header>

<?php /*倒计时广告**/ ?>
<?php  if($countdowns = Mage::getModel('ibanners/group')->loadByCode('header_countdown')->getBannerCollection()):?>
    <?php foreach($countdowns as $cd){ $countdown = $cd;break;}?>
    <?php if( strtotime($countdown->getAltText()) > time()  ):?>
        <div class="header_countdown">
            <div onclick="window.location.href='<?php echo $countdown->getUrl(); ?>'">
                <?php
                $imag_src = $countdown->getImageUrl();
                if($imag_src){
                    echo '<img src="'.$imag_src.'"/>';
                }
                ?>
                <span id="header_countdown" class="PositionAbsolute"></span>
            </div>
            <?php $date_time = strtotime($countdown->getAltText()); ?>
            <script type="text/javascript">
                jQuery(document).ready(function($){
                    countdown('header_countdown', <?php echo date("Y",$date_time)?>, <?php echo date("m",$date_time)?>, <?php echo date("d",$date_time)?>, <?php echo date("H",$date_time)?>, <?php echo date("i",$date_time)?>, <?php echo date("s",$date_time)?>);
                });
            </script>
        </div>
    <?php endif;?>
<?php endif; ?>
