<?php if($this->canShowBlock()): ?>
    <div class="shopby">
        <dl>
            <?php if($this->canShowOptions()): ?>
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                    <?php if($_filter->getItemsCount()): ?>
                        <dt>Shop By <?php echo $this->__($_filter->getName()) ?></dt>
                        <dd><?php echo $_filter->getHtml() ?></dd>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>

        </dl>
    </div>




<div class="block block-layered-nav">

    <div class="block-content">

        <?php echo $this->getStateHtml() ?>

        <?php if ($this->getLayer()->getState()->getFilters()): ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
